secretKey: XvcAzlTaOp1KnkOQ1z/ikw==

# Change default server ports
server:
  rootPath: /crypto/api/*
  applicationConnectors:
    - type: http
      port: 8100
  adminConnectors:
    - type: http
      port: 8101